import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './styles/global.css'
import { registerSW } from 'virtual:pwa-register'

// Register the service worker generated by vite-plugin-pwa.
// In supported browsers, this enables offline caching and installability.
registerSW({
    immediate: true,
})

ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode>
        <App />
    </React.StrictMode>,
)